### ISSUE TITLE
似乎是证书问题

### ISSUE THREAD

**Issue by EndureBlaze** [yeshan333/actions-for-hexo-blog#6]
你好，我参考了你的部署脚本，但是在最后 deploy 时出现了 ` git@github.com: Permission denied (publickey).` 报错，导致没法推送，这是为什么呢？我已经在我的账号下配置了公钥，并且在 secrets 配置了私钥。

**Comment by yeshan333** [comment]
本地用的私钥，secrets用的公钥,即 id_rsa.pub&nbsp;



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haocun Ni"<notifications@github.com&gt;; 
发送时间: 2020年11月16日(星期一) 下午5:12
收件人: "yeshan333/actions-for-hexo-blog"<actions-for-hexo-blog@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [yeshan333/actions-for-hexo-blog] 似乎是证书问题 (#6)





 
你好，我参考了你的部署脚本，但是在最后 deploy 时出现了  git@github.com: Permission denied (publickey). 报错，导致没法推送，这是为什么呢？我已经在我的账号下配置了公钥，并且在 secrets 配置了私钥。

**Comment by yeshan333** [comment]
哦，错了，具体日志可以给我看看吗&nbsp;



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haocun Ni"<notifications@github.com&gt;; 
发送时间: 2020年11月16日(星期一) 下午5:12
收件人: "yeshan333/actions-for-hexo-blog"<actions-for-hexo-blog@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [yeshan333/actions-for-hexo-blog] 似乎是证书问题 (#6)





 
你好，我参考了你的部署脚本，但是在最后 deploy 时出现了  git@github.com: Permission denied (publickey). 报错，导致没法推送，这是为什么呢？我已经在我的账号下配置了公钥，并且在 secrets 配置了私钥。
